name: Deploy to docker hub

on:
  push:
    branches:
      - 'develop'
env:
  RC_NAME: atgenomix.azurecr.io/atgenomix/seqslab_runtime-1.2_ubuntu-16.04_hail-annotation

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set current date as env variable
        run: |
          echo "::set-env name=NOW::$(date +'%m%d%H%M')"
          echo $NOW

      - name: Az Login and Pull
        run: |
          az login --service-principal --username ${{ secrets.AZ_APP_CLIENT_ID }} --password ${{ secrets.AZ_APP_CLIENT_KEY }} --tenant ${{ secrets.AZ_APP_TENANT }}
          az acr login --name atgenomix

      - name: Build image
        run: |
          docker build --no-cache -t ${RC_NAME} atgenomix
          docker tag ${RC_NAME} ${RC_NAME}:$NOW
          docker tag ${RC_NAME} ${RC_NAME}:latest

      - name: Push image
        run: |
          docker push ${RC_NAME}:$NOW
          docker push ${RC_NAME}:latest