name: Deploy to docker hub

on:
  push:
    branches:
      - '*'
env:
  RC_NAME: atgenomix.azurecr.io/atgenomix/seqslab_runtime-1.2_ubuntu-16.04_hail-annotation

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout hail code
        uses: actions/checkout@v2
        with:
          path: hail

      - name: Checkout runtime code
        uses: actions/checkout@v2
        with:
          ref: annotation
          repository: AnomeGAP/Seqslab_Runtime
          token: ${{ secrets.PAT_SEQSLAB_RUNTIME }}
          path: runtime

      - name: Set current date as env variable
        run: |
          echo "::set-env name=NOW::$(date +'%m%d%H%M')"
          echo $NOW

      - name: Build image
        run: |
          docker build --cache-from ${RC_NAME}:cache -t ${RC_NAME} /home/runner/work/hail/hail/runtime/1.2_annotation
          docker tag ${RC_NAME} ${RC_NAME}:$NOW
          docker tag ${RC_NAME} ${RC_NAME}:cache
          docker tag ${RC_NAME} ${RC_NAME}:latest

      - name: Az Login and Push
        run: |
          az login --service-principal --username ${{ secrets.AZ_APP_CLIENT_ID }} --password ${{ secrets.AZ_APP_CLIENT_KEY }} --tenant ${{ secrets.AZ_APP_TENANT }}
          az acr login --name atgenomix

      - name: Push Cache to docker registry
        uses: actions-hub/docker@master
        if: always()
        with:
          args: push ${RC_NAME}:cache

      - name: Push to docker registry
        uses: actions-hub/docker@master
        if: always()
        with:
          args: push ${RC_NAME}:$NOW

      - name: Push Cache to docker registry
        uses: actions-hub/docker@master
        if: always()
        with:
          args: push ${RC_NAME}:latest